apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  name: argocd-aggregate-admin
rules:
- apiGroups:
  - argoproj.io
  resources:
  - argocds
  - appprojects
  - applications
  verbs:
  - '*'
