apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: argocd-operator
  name: argocd-operator-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 8443
    targetPort: 8080
  selector:
    control-plane: argocd-operator
