# Creates a ManagedClusterSet resource
#
# Requires:
#   * To associate a cluster to this ManagedClusterSet, add the following label:
#       metadata:
#         labels:
#            cluster.open-cluster-management.io/clusterset: all-openshift-clusters
#            ...
#            

---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ManagedClusterSet
metadata:
  name: all-openshift-clusters
spec: {}