apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: {{ .Release.Namespace }}
spec:
  image: {{ .Values.global.application_controller.image }}
  version: {{ .Values.global.application_controller.tag }}
  controller:
    enabled: true
    processors: {}
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi
    env:
      {{- if eq .Values.global.reconcile_scope "All-Namespaces"}}
      - name: ARGOCD_APPLICATION_NAMESPACES
        valueFrom:
          configMapKeyRef:
            name: argocd-cmd-params-cm
            key: application.namespaces
            optional: true
      {{- end }}
      {{- if .Values.global.proxyConfig.HTTP_PROXY }}
      - name: HTTP_PROXY
        value: {{ .Values.global.proxyConfig.HTTP_PROXY }}
      {{- end }}
      {{- if .Values.global.proxyConfig.HTTPS_PROXY }}
      - name: HTTPS_PROXY
        value: {{ .Values.global.proxyConfig.HTTPS_PROXY }}
      {{- end }}
      {{- if .Values.global.proxyConfig.NO_PROXY }}
      - name: NO_PROXY
        value: {{ .Values.global.proxyConfig.NO_PROXY }}
      {{- end }}
  redis:
    image: {{ .Values.global.redis.image }}
    version: {{ .Values.global.redis.tag }}
    enabled: true
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  repo:
    image: {{ .Values.global.application_controller.image }}
    version: {{ .Values.global.application_controller.tag }}
    enabled: true
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 256Mi
    env:
      {{- if .Values.global.proxyConfig.HTTP_PROXY }}
      - name: HTTP_PROXY
        value: {{ .Values.global.proxyConfig.HTTP_PROXY }}
      {{- end }}
      {{- if .Values.global.proxyConfig.HTTPS_PROXY }}
      - name: HTTPS_PROXY
        value: {{ .Values.global.proxyConfig.HTTPS_PROXY }}
      {{- end }}
      {{- if .Values.global.proxyConfig.NO_PROXY }}
      - name: NO_PROXY
        value: {{ .Values.global.proxyConfig.NO_PROXY }}
      {{- end }}
  rbac:
    defaultPolicy: "role:admin"
    policy: |
      g, cluster-admins, role:admin
  applicationSet:
    enabled: false
  grafana:
    enabled: false
  ha:
    enabled: false
  server:
    enabled: false
  monitoring:
    enabled: false
  notifications:
    enabled: false
  prometheus:
    enabled: false
