apiVersion: v1
kind: ServiceAccount
metadata:
  name: openshift-gitops-argocd-application-controller
  namespace: {{ .Release.Namespace }}
imagePullSecrets:
- name: open-cluster-management-image-pull-credentials
