{{- $existing := lookup "rbac.authorization.k8s.io/v1" "ClusterRoleBinding" "" "openshift-gitops-argocd-application-controller" }}
{{- if not $existing }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-gitops-argocd-application-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: {{ .Release.Namespace }}
{{- end }}
